Dev/standardized ux
Unity-Technologies/upm-package-cinemachine pull request #107
Opened 2020-09-29 12:41 UTC by gaborkb

Moved Cinemachine menu to GameObject.
Removed About page.

2020-09-29 13:44 UTC, JulienDidierjean commented
Hi Krisztian, 
Thanks for putting me as a reviewer...
Here are my comments based on the screenshot you posted:
 - I would drop the "Create" from each line, none of the the other entries in this "Create" menu has one
 - I'm quite sure I would not put an enable/disable option there: "Storyboard Global Mute" 
I think we should put it under Cinemachine Preferences maybe... 
Question: Is this option not present in the UI of all the Cinemachine cameras ? Maybe it's enough...
Can you tell me why it's been added there in the first place ?
(I can post this comment in the cinemachine-core channel to trigger discussions if you want...

2020-09-29 16:02 UTC, gaborkb commented
> * I would drop the "Create" from each line, none of the the other entries in this "Create" menu has one

Ok!

2020-09-29 16:02 UTC, gaborkb commented
> * I'm quite sure I would not put an enable/disable option there: "Storyboard Global Mute"
>   I think we should put it under Cinemachine Preferences maybe...
>   Question: Is this option not present in the UI of all the Cinemachine cameras ? Maybe it's enough...
>   Can you tell me why it's been added there in the first place ?
>   (I can post this comment in the cinemachine-core channel to trigger discussions if you want...

Yes, please post it, as I am not sure what the answer is.

2020-10-16 20:56 UTC, glabute requested changes
You also need to go through the manual (the Documentation~ folder) and correct any references to the Cinemachine menu

2020-10-16 20:56 UTC, glabute commented on Editor/Editors/CinemachineStoryboardEditor.cs
> +        const string StoryboardGlobalMuteMenuName = "GameObject/Cinemachine/Storyboard Global Mute";
Leave this in the Cinemachine menu for now (maybe as the only thing).
We need to create a preferences page to move it to.  We can save that for another PR.
(so just revert this change)

2020-10-16 20:56 UTC, glabute commented on Extras~/ReleaseNotes.txt
> +- UI update - Moved Cinemachine menu to GameObject Create menu and Right Click context menu for Hierachy window.
This entire file can now be deleted, since it was only ever used in the About window.

2020-10-20 16:11 UTC, glabute approved these changes

2020-10-20 16:33 UTC, merged